use std::fmt;

use crate::source::Span;

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Token {
    pub kind: TokenKind,
    pub span: Span,
}

impl Token {
    pub fn new(kind: TokenKind, span: Span) -> Self {
        Self { kind, span }
    }
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub enum TokenKind {
    Ident(String),
    Keyword(Keyword),
    IntLiteral(String),
    FloatLiteral(String),
    StringLiteral(String),
    CharLiteral(String),
    LineComment(String),
    DocLineComment(String),
    BlockComment(String),
    DocBlockComment(String),
    HoleIdent(String),
    Unknown(char),
    LParen,
    RParen,
    LBrace,
    RBrace,
    LBracket,
    RBracket,
    Comma,
    Dot,
    DotDot,
    Colon,
    DoubleColon,
    Semicolon,
    Plus,
    Minus,
    Star,
    DoubleStar,
    Slash,
    Percent,
    Eq,
    EqEq,
    Bang,
    BangEq,
    Lt,
    LtEq,
    Gt,
    GtEq,
    Amp,
    AmpAmp,
    Pipe,
    PipePipe,
    Arrow,
    FatArrow,
    Question,
    Hash,
    At,
    Underscore,
    Eof,
}

impl TokenKind {
    pub fn name(&self) -> &'static str {
        match self {
            Self::Ident(_) => "identifier",
            Self::Keyword(_) => "keyword",
            Self::IntLiteral(_) => "integer literal",
            Self::FloatLiteral(_) => "float literal",
            Self::StringLiteral(_) => "string literal",
            Self::CharLiteral(_) => "character literal",
            Self::LineComment(_) => "line comment",
            Self::DocLineComment(_) => "doc line comment",
            Self::BlockComment(_) => "block comment",
            Self::DocBlockComment(_) => "doc block comment",
            Self::HoleIdent(_) => "hole",
            Self::Unknown(_) => "unknown",
            Self::LParen => "`(`",
            Self::RParen => "`)`",
            Self::LBrace => "`{`",
            Self::RBrace => "`}`",
            Self::LBracket => "`[`",
            Self::RBracket => "`]`",
            Self::Comma => "`,`",
            Self::Dot => "`.`",
            Self::DotDot => "`..`",
            Self::Colon => "`:`",
            Self::DoubleColon => "`::`",
            Self::Semicolon => "`;`",
            Self::Plus => "`+`",
            Self::Minus => "`-`",
            Self::Star => "`*`",
            Self::DoubleStar => "`**`",
            Self::Slash => "`/`",
            Self::Percent => "`%`",
            Self::Eq => "`=`",
            Self::EqEq => "`==`",
            Self::Bang => "`!`",
            Self::BangEq => "`!=`",
            Self::Lt => "`<`",
            Self::LtEq => "`<=`",
            Self::Gt => "`>`",
            Self::GtEq => "`>=`",
            Self::Amp => "`&`",
            Self::AmpAmp => "`&&`",
            Self::Pipe => "`|`",
            Self::PipePipe => "`||`",
            Self::Arrow => "`->`",
            Self::FatArrow => "`=>`",
            Self::Question => "`?`",
            Self::Hash => "`#`",
            Self::At => "`@`",
            Self::Underscore => "`_`",
            Self::Eof => "end of file",
        }
    }
}

impl fmt::Display for TokenKind {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Ident(value) => write!(f, "Ident({value})"),
            Self::Keyword(value) => write!(f, "Keyword({})", value.as_str()),
            Self::IntLiteral(value) => write!(f, "IntLiteral({value})"),
            Self::FloatLiteral(value) => write!(f, "FloatLiteral({value})"),
            Self::StringLiteral(value) => write!(f, "StringLiteral({value:?})"),
            Self::CharLiteral(value) => write!(f, "CharLiteral({value:?})"),
            Self::LineComment(_) => write!(f, "LineComment"),
            Self::DocLineComment(_) => write!(f, "DocLineComment"),
            Self::BlockComment(_) => write!(f, "BlockComment"),
            Self::DocBlockComment(_) => write!(f, "DocBlockComment"),
            Self::HoleIdent(value) => write!(f, "HoleIdent({value})"),
            Self::Unknown(value) => write!(f, "Unknown({value})"),
            _ => write!(f, "{}", self.name()),
        }
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum Keyword {
    As,
    Async,
    Await,
    Auto,
    Borrow,
    Box,
    Break,
    Cap,
    Chan,
    Closed,
    Const,
    Continue,
    Defer,
    Do,
    Effect,
    Else,
    Ensures,
    Enum,
    Erased,
    False,
    Fn,
    For,
    Forall,
    Ghost,
    Given,
    If,
    Impl,
    Implicit,
    Impossible,
    Import,
    In,
    Invariant,
    Let,
    Linear,
    Loop,
    Match,
    Mod,
    Move,
    Mut,
    Package,
    Partial,
    Post,
    Pre,
    Proof,
    Pub,
    Recv,
    Ref,
    Requires,
    Return,
    Rewrite,
    Select,
    Send,
    Shared,
    Spawn,
    Static,
    Struct,
    Terminates,
    Total,
    Trait,
    True,
    Type,
    Unsafe,
    Unique,
    Use,
    Where,
    While,
    With,
    Yield,
}

impl Keyword {
    pub fn from_ident(text: &str) -> Option<Self> {
        Some(match text {
            "as" => Self::As,
            "async" => Self::Async,
            "await" => Self::Await,
            "auto" => Self::Auto,
            "borrow" => Self::Borrow,
            "box" => Self::Box,
            "break" => Self::Break,
            "cap" => Self::Cap,
            "chan" => Self::Chan,
            "closed" => Self::Closed,
            "const" => Self::Const,
            "continue" => Self::Continue,
            "defer" => Self::Defer,
            "do" => Self::Do,
            "effect" => Self::Effect,
            "else" => Self::Else,
            "ensures" => Self::Ensures,
            "enum" => Self::Enum,
            "erased" => Self::Erased,
            "false" => Self::False,
            "fn" => Self::Fn,
            "for" => Self::For,
            "forall" => Self::Forall,
            "ghost" => Self::Ghost,
            "given" => Self::Given,
            "if" => Self::If,
            "impl" => Self::Impl,
            "implicit" => Self::Implicit,
            "impossible" => Self::Impossible,
            "import" => Self::Import,
            "in" => Self::In,
            "invariant" => Self::Invariant,
            "let" => Self::Let,
            "linear" => Self::Linear,
            "loop" => Self::Loop,
            "match" => Self::Match,
            "mod" => Self::Mod,
            "move" => Self::Move,
            "mut" => Self::Mut,
            "package" => Self::Package,
            "partial" => Self::Partial,
            "post" => Self::Post,
            "pre" => Self::Pre,
            "proof" => Self::Proof,
            "pub" => Self::Pub,
            "recv" => Self::Recv,
            "ref" => Self::Ref,
            "requires" => Self::Requires,
            "return" => Self::Return,
            "rewrite" => Self::Rewrite,
            "select" => Self::Select,
            "send" => Self::Send,
            "shared" => Self::Shared,
            "spawn" => Self::Spawn,
            "static" => Self::Static,
            "struct" => Self::Struct,
            "terminates" => Self::Terminates,
            "total" => Self::Total,
            "trait" => Self::Trait,
            "true" => Self::True,
            "type" => Self::Type,
            "unsafe" => Self::Unsafe,
            "unique" => Self::Unique,
            "use" => Self::Use,
            "where" => Self::Where,
            "while" => Self::While,
            "with" => Self::With,
            "yield" => Self::Yield,
            _ => return None,
        })
    }

    pub fn as_str(self) -> &'static str {
        match self {
            Self::As => "as",
            Self::Async => "async",
            Self::Await => "await",
            Self::Auto => "auto",
            Self::Borrow => "borrow",
            Self::Box => "box",
            Self::Break => "break",
            Self::Cap => "cap",
            Self::Chan => "chan",
            Self::Closed => "closed",
            Self::Const => "const",
            Self::Continue => "continue",
            Self::Defer => "defer",
            Self::Do => "do",
            Self::Effect => "effect",
            Self::Else => "else",
            Self::Ensures => "ensures",
            Self::Enum => "enum",
            Self::Erased => "erased",
            Self::False => "false",
            Self::Fn => "fn",
            Self::For => "for",
            Self::Forall => "forall",
            Self::Ghost => "ghost",
            Self::Given => "given",
            Self::If => "if",
            Self::Impl => "impl",
            Self::Implicit => "implicit",
            Self::Impossible => "impossible",
            Self::Import => "import",
            Self::In => "in",
            Self::Invariant => "invariant",
            Self::Let => "let",
            Self::Linear => "linear",
            Self::Loop => "loop",
            Self::Match => "match",
            Self::Mod => "mod",
            Self::Move => "move",
            Self::Mut => "mut",
            Self::Package => "package",
            Self::Partial => "partial",
            Self::Post => "post",
            Self::Pre => "pre",
            Self::Proof => "proof",
            Self::Pub => "pub",
            Self::Recv => "recv",
            Self::Ref => "ref",
            Self::Requires => "requires",
            Self::Return => "return",
            Self::Rewrite => "rewrite",
            Self::Select => "select",
            Self::Send => "send",
            Self::Shared => "shared",
            Self::Spawn => "spawn",
            Self::Static => "static",
            Self::Struct => "struct",
            Self::Terminates => "terminates",
            Self::Total => "total",
            Self::Trait => "trait",
            Self::True => "true",
            Self::Type => "type",
            Self::Unsafe => "unsafe",
            Self::Unique => "unique",
            Self::Use => "use",
            Self::Where => "where",
            Self::While => "while",
            Self::With => "with",
            Self::Yield => "yield",
        }
    }
}
